### PR TITLE
Fix typo in the readme

### PR DESCRIPTION
**Pull request by jdreesen**

### CODE REVIEW

**Review by janmartenjongerius — APPROVED** [review]
I'm expecting to release a beta of 2.0 in the next two weeks, at which point that becomes the master branch, so expect this change to only live in the 1.2 branch ;-)

Thanks for the contribution!

**Comment by jdreesen** [comment]
So, should I send another PR targeting the `2.0` branch?

**Comment by janmartenjongerius** [comment]
> So, should I send another PR targeting the `2.0` branch?

@jdreesen  That's quite alright, thanks :) 

The documentation for version 2 is a complete rewrite. I've been working on it for weeks, but because a large part refers to unwritten parts, I've not created a commit for it.

If you'd like to help out, I'd really appreciate it if you could check out the migration guide I'm adding to the documentation, to see if it's incomplete, incorrect or could be improved. I'm expecting that to go up later this week.

**Comment by janmartenjongerius** [comment]
@jdreesen I've given it some more thought and I appreciate contributions too much, so this will get merged into master and I'll rebase `2.0` later on. That's a problem for future me.

Again, thanks for the contribution! I hope you like the library and especially the degree of agency you'll get from version 2

**Comment by jdreesen** [comment]
So far, I really like it. But I fear that I'll have to stay on v1 for some time as we're stuck to PHP 7.4 in our current project.

**Pull request merged**
